version: "3"

services:
    app:
      container_name: laravel_vuex2_app
      build: ./api/docker
      volumes:
        - ./api:/var/www
      ports:
        - "9000:9000"
      command: php artisan swoole:http start
      depends_on: 
        - mysql

    mysql:
        container_name: "laravel_vuex2_mysql"
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        restart: on-failure:2
        ports:
            - "3306:3306"
        volumes:
            - "./api/docker/dbdata:/var/lib/mysql"        
        environment:
            MYSQL_DATABASE: imoveis
            MYSQL_ROOT_PASSWORD: 102030 
            MYSQL_USER: root
            MYSQL_PASSWORD: 102030

    # SPA com Vuex
    # front:
    #   container_name: "laravel_vuex2_front"
    #   build: ./front
    #   volumes:
    #     - ./front:/app:rw
    #     - /front/node_modules
    #   ports:
    #     - "80:3000"
    #   depends_on: 
    #     - mysql        
    #     - app